package es.upm.dit.isst.rgpd.test;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import es.upm.dit.isst.rgpd.dao.EvaluadorDAO;
import es.upm.dit.isst.rgpd.dao.EvaluadorDAOImplementation;
import es.upm.dit.isst.rgpd.model.Evaluador;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class RegistroEvaluador {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty( "webdriver.chrome.driver", "chromedriver.exe");
		driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
	  EvaluadorDAO edao = EvaluadorDAOImplementation.getInstance();
	  Evaluador evaluador = edao.read("nuevoevaluador@upm.es");
	  edao.delete(evaluador);
	  driver.quit();
  }
  @Test
  public void RegistroEvaluador() {
    driver.get("http://localhost:8080/ISST2019/RegisterView.jsp");
    driver.manage().window().setSize(new Dimension(1280, 680));
    driver.findElement(By.name("name")).click();
    driver.findElement(By.cssSelector(".box")).click();
    driver.findElement(By.name("name")).sendKeys("Nuevo Evaluador");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("nuevoevaluador@upm.es");
    driver.findElement(By.name("password")).sendKeys("pass");
    driver.findElement(By.name("area")).sendKeys("area");
    driver.findElement(By.name("grupo")).sendKeys("grupo");
    driver.findElement(By.cssSelector(".col-6:nth-child(2) > label")).click();
    driver.findElement(By.cssSelector(".special")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("nuevoevaluador@upm.es");
    driver.findElement(By.name("password")).sendKeys("pass");
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("header b")).click();
    assertThat(driver.findElement(By.cssSelector("header b")).getText(), is("¡Bienvenido evaluador Nuevo Evaluador!"));
    driver.findElement(By.linkText("Log out")).click();
  }
}
